services:
  subscriptions:
    container_name: subscriptions
    restart: unless-stopped
    build:
      context: .
      dockerfile: deploy/Dockerfile
    env_file: '.env'
    ports: 
      - ${BIND_PORT}:${BIND_PORT}
    depends_on:
      postgres: 
        condition: service_healthy


  postgres:
    container_name: ${POSTGRES_HOST}
    restart: unless-stopped
    image: postgres:alpine
    env_file: '.env'
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 3


volumes:
  postgres_data:
    driver: local
